# Generated by Django 5.1 on 2024-08-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auser',
            old_name='name_field',
            new_name='name',
        ),
    ]
