# Generated by Django 5.1 on 2024-08-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_name_field_auser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
